WestuaFFI/Internet/Models/Slide.cs
using System.Threading;

namespace Internet.Models
{
    public partial class Slide
    {
        public string Description
        {
            get
            {
                switch (Thread.CurrentThread.CurrentCulture.TwoLetterISOLanguageName)
                {
                    case "en":
                        return Description_en;
                    case "ru":
                        return Description_ru;
                    default:
                        return Description_ua;
                }
            }
        }
    }
}

WestuaFFI/Internet/Areas/Admin/Controllers/SlidesController.cs
using System;
using System.Data;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Internet.Models;

namespace Internet.Areas.Admin.Controllers
{ 
    public class SlidesController : Controller
    {
        private ffiEntities db = new ffiEntities();

        public ActionResult GetImage(Guid slideId)
        {
            var slide = db.Slides.FirstOrDefault(entry => entry.Id == slideId);
            var arr = slide.Image == null ? new byte[0] : slide.Image;
            return File(arr, "image/png");
        }
 
        //
        // GET: /Admin/Slides/

        public ViewResult Index()
        {
            return View(db.Slides.ToList());
        }

        //
        // GET: /Admin/Slides/Details/5

        public ViewResult Details(Guid id)
        {
            Slide slide = db.Slides.Single(s => s.Id == id);
            return View(slide);
        }

        //
        // GET: /Admin/Slides/Create

        public ActionResult Create()
        {
            return View();
        } 

        //
        // POST: /Admin/Slides/Create

        [HttpPost]
        public ActionResult Create(Slide slide, HttpPostedFileBase slideImg)
        {
            if (ModelState.IsValid)
            {
                if (slideImg != null)
                    using (var ms = new MemoryStream())
                    {
                        slideImg.InputStream.CopyTo(ms);
                        byte[] imgArray = ms.GetBuffer();
                        slide.Image = imgArray; //new WebImage(imgArray).Resize(200, 200).GetBytes("png");
                    }

 
                slide.Id = Guid.NewGuid();
                db.Slides.AddObject(slide);
                db.SaveChanges();
                return RedirectToAction("Index");  
            }

            return View(slide);
        }
        
        //
        // GET: /Admin/Slides/Edit/5
 
        public ActionResult Edit(Guid id)
        {
            Slide slide = db.Slides.Single(s => s.Id == id);
            return View(slide);
        }

        //
        // POST: /Admin/Slides/Edit/5

        [HttpPost]
        public ActionResult Edit(Slide slide, HttpPostedFileBase slideImg)
        {
            if (ModelState.IsValid)
            {
                var oldSlide = db.Slides.FirstOrDefault(entry => entry.Id == slide.Id);
                if (slideImg != null)
                    using (var ms = new MemoryStream())
                    {
                        slideImg.InputStream.CopyTo(ms);
                        byte[] imgArray = ms.GetBuffer();
                        slide.Image = imgArray; //new WebImage(imgArray).Resize(200, 200).GetBytes("png");
                    }
                else
                    slide.Image = oldSlide.Image;
 
                db.Slides.Detach(oldSlide);
                db.Slides.Attach(slide);
                db.ObjectStateManager.ChangeObjectState(slide, EntityState.Modified);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(slide);
        }

        //
        // GET: /Admin/Slides/Delete/5
 
        public ActionResult Delete(Guid id)
        {
            Slide slide = db.Slides.Single(s => s.Id == id);
            return View(slide);
        }

        //
        // POST: /Admin/Slides/Delete/5

        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(Guid id)
        {            
            Slide slide = db.Slides.Single(s => s.Id == id);
            db.Slides.DeleteObject(slide);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

WestuaFFI/Internet/Areas/Admin/Views/Slides/Create.cshtml
@model Internet.Models.Slide
@{
    ViewBag.Title = "Create";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}
<h2>
    Create</h2>
@*<script src="@Url.Content("~/Scripts/jquery.validate.min.js")" type="text/javascript"></script>*@
<script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")" type="text/javascript"></script>
@using (Html.BeginForm("Create", "Slides", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
   @Html.Partial("_SlideForm", Model)
}
<div>
    @Html.ActionLink("Back to List", "Index")
</div>

WestuaFFI/Internet/Areas/Admin/Views/Slides/Delete.cshtml
@model Internet.Models.Slide

@{
    ViewBag.Title = "Delete";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<fieldset>
    <legend>Slide</legend>

    <div class="display-label">Url</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Url)
    </div>

    <div class="display-label">Description</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Description)
    </div>
</fieldset>
@using (Html.BeginForm()) {
    <p>
        <input type="submit" value="Delete" /> |
        @Html.ActionLink("Back to List", "Index")
    </p>
}

WestuaFFI/Internet/Areas/Admin/Views/Slides/Details.cshtml
@model Internet.Models.Slide

@{
    ViewBag.Title = "Details";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<h2>Details</h2>

<fieldset>
    <legend>Slide</legend>

    <div class="display-label">Url</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Url)
    </div>

    <div class="display-label">Description</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Description)
    </div>
    <img src="@Url.Action("GetImage", "Slides", new { slideId = Model.Id })"/>
    
</fieldset>
<p>
    @Html.ActionLink("Edit", "Edit", new { id=Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

WestuaFFI/Internet/Areas/Admin/Views/Slides/Edit.cshtml
@model Internet.Models.Slide
@{
    ViewBag.Title = "Edit";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}
<h2>
    Edit</h2>
@*<script src="@Url.Content("~/Scripts/jquery.validate.min.js")" type="text/javascript"></script>*@
<script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")" type="text/javascript"></script>
@using (Html.BeginForm("Edit", "Slides", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.Partial("_SlideForm", Model)
}
<div>
    @Html.ActionLink("Back to List", "Index")
</div>

WestuaFFI/Internet/Areas/Admin/Views/Slides/Index.cshtml
@model IEnumerable<Internet.Models.Slide>

@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table>
    <tr>
        <th>
            Url
        </th>
        <th>
            Description
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Url)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Description)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.Id }) |
            @Html.ActionLink("Details", "Details", new { id=item.Id }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.Id })
        </td>
    </tr>
}

</table>

WestuaFFI/Internet/Areas/Admin/Views/Slides/_SlideForm.cshtml
@model Internet.Models.Slide

 @Html.ValidationSummary(true)
    <fieldset>
        <legend>Slide</legend>
        <div class="editor-label">
            @Html.LabelFor(model => model.Url)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Url)
            @Html.ValidationMessageFor(model => model.Url)
        </div>
        <div class="editor-label">
            @Html.LabelFor(model => model.Description_ua)
        </div>
        <div class="editor-field">
            @Html.TextAreaFor(model => model.Description_ua, new { @class = "redactor" })
            @Html.ValidationMessageFor(model => model.Description_ua)
        </div>
        <div class="editor-label">
            @Html.LabelFor(model => model.Description_ru)
        </div>
        <div class="editor-field">
            @Html.TextAreaFor(model => model.Description_ru, new { @class = "redactor" })
            @Html.ValidationMessageFor(model => model.Description_ru)
        </div>
        <div class="editor-label">
            @Html.LabelFor(model => model.Description_en)
        </div>
        <div class="editor-field">
            @Html.TextAreaFor(model => model.Description_en, new { @class = "redactor" })
            @Html.ValidationMessageFor(model => model.Description_en)
        </div>
        Image
        <input type="file" name="slideImg" id="slideImg" accept="image/x-png, image/gif, image/jpeg" />
        <p>
            <input type="submit" value="Create" />
        </p>
    </fieldset>