WestuaFFI/Internet/Controllers/ArticlesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Internet.Controllers
{
    public class ArticlesController : Controller
    {
        //
        // GET: /Articles/

        public ActionResult Index()
        {
            return View();
        }


        public ActionResult FuelEconomy()
        {
            return View();
        }

        public ActionResult HowItWorks()
        {
            return View();
        }
        
        public ActionResult Certifications()
        {
            return View();
        }

        public ActionResult GettingStarted()
        {
            return View();
        }

        public ActionResult Presentation()
        {
            return View();
        }

        public ActionResult Instruction()
        {
            return View();
        } 
        
        public ActionResult Business()
        {
            return View();
        }
    }
}

WestuaFFI/Internet/Controllers/BannersController.cs
using System;
using System.Data;
using System.Data.Objects;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Helpers;
using System.Web.Mvc;
using Internet.Extensions;
using Internet.Models;

namespace Internet.Controllers
{
    public class BannersController : Controller
    {

        private ffiEntities db = new ffiEntities();

        public ActionResult GetImage(Guid id)
        {
            var banner = db.Banners.FirstOrDefault(entry => entry.Id == id);
            var arr = banner.Image == null ? new byte[0] : banner.Image;
            return File(arr, "image/png");
        }

        [Authorize]
        public ActionResult Update(Banner banner, HttpPostedFileBase bannerImg)
        {
            var partner = db.Partners.FirstOrDefault(entry => entry.Id == banner.PartnerId);

            if (string.IsNullOrEmpty(banner.Url) || bannerImg == null) return RedirectToAction("Edit", "Partners", new { id = partner.User.UserName }).Warning((string.Format("{0} {1}", "Banner", Resources.labels.Incorrect)));
            if (partner != null)
            {
                if (bannerImg != null)
                    using (var ms = new MemoryStream())
                    {
                        bannerImg.InputStream.CopyTo(ms);
                        byte[] imgArray = ms.GetBuffer();
                        banner.Image = new WebImage(imgArray).Resize(450, 70).Crop(1, 1).GetBytes("png");
                    }
                if (partner.Banners.Any())
                {
                    var oldBanner = db.Banners.FirstOrDefault(entry => entry.Id == banner.Id);
                    oldBanner.Url = banner.Url;
                    oldBanner.Image = banner.Image;
                }
                else
                {
                    banner.Id = Guid.NewGuid();
                    db.Banners.AddObject(banner);
                }
                db.SaveChanges();
                return RedirectToAction("Edit", "Partners", new { id = partner.User.UserName }).Warning(@Resources.labels.AccountUpdated);
            }
            return RedirectToAction("Edit", "Partners", new { id = partner.User.UserName }).Warning("Error, please contact administrator");
        }

        public ActionResult Remove(Guid id)
        {
            var banner = db.Banners.FirstOrDefault(entry => entry.Id == id);
            var userName = banner.Partner.User.UserName;
            db.Banners.DeleteObject(banner);
            db.SaveChanges();
            return RedirectToAction("Edit", "Partners", new { id = userName }).Warning(@Resources.labels.AccountUpdated);
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

WestuaFFI/Internet/Controllers/FAQsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Internet.Models;

namespace Internet.Controllers
{ 
    public class FAQsController : Controller
    {
        private ffiEntities db = new ffiEntities();

        //
        // GET: /FAQs/

        public ViewResult Index()
        {
            return View(db.FAQs.Where(entry=>entry.ShowOnPartnerPanel == false).OrderBy(entry=>entry.Question_ru).ToList());
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

WestuaFFI/Internet/Controllers/ResultsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Internet.Extensions;
using Internet.Helpers;
using Internet.Models;

namespace Internet.Controllers
{ 
    public class ResultsController : Controller
    {
        private ffiEntities db = new ffiEntities();

        //
        // GET: /Results/

        public class ResultsModelView
        {
            private static ffiEntities db = new ffiEntities();

            public List<string> Manufacturers = db.Results.Where(entry=>entry.isActive).Select(entry => entry.Manufacturer).ToList();
            public List<string> Models = new List<string>();
            public Result Result { get; set; }
        }

        public ViewResult Index(string manufacturer, string model)
        {
            var resultView = new ResultsModelView();            
            if (!string.IsNullOrEmpty(manufacturer))
            {
                resultView.Models =
                    db.Results.Where(entry => entry.Manufacturer == manufacturer && entry.isActive).Select(entry => entry.Model).ToList();
                if (!string.IsNullOrEmpty(model))
                    resultView.Result =
                        db.Results.FirstOrDefault(entry => entry.Manufacturer == manufacturer && entry.Model == model && entry.isActive);
            }
            return View(resultView);
        }

        //
        // GET: /Results/Details/5

        public ViewResult Details(Guid id)
        {
            Result result = db.Results.Single(r => r.Id == id);
            return View(result);
        }

        public ActionResult ContactOwner(string video, string sendTo, string manufacturer, string model, string contacts)
        {
            EmailHelper.Instance.SendResultContactOwner(video, sendTo, contacts);
            return RedirectToAction("Index", new {Manufacturer = manufacturer, Model = model}).Warning(Resources.labels.RequestCreated);
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

WestuaFFI/Internet/Views/Shared/_Flash.cshtml
<div id="flash-messages" class="alert" style="display:none;">    
    <a class="close" href="#">&times;</a>
    <p></p>
</div>

<script type="text/javascript">
    $(function () {
        $("#flash-messages").flashMessage();
    });
</script>

WestuaFFI/Internet/Views/Shared/_Layout.cshtml
@using Internet.Helpers
@using Internet.Models
@using Internet.RoutingHelpers
@{
    var siteOnwer = SubdomainHelper.GetSiteOwner();
    var partner = Partner.CurrentUserAsPartner;

    var partnerLink = partner == null ? Url.Action("Business", "Articles") : Url.Action("Edit", "Partners", new { id = User.Identity.Name });
}
<!DOCTYPE html>
<html>
<head>
    <title>@Resources.labels.Title - @ViewBag.Title</title>
    <meta charset="windows-1251">
    @RenderSection("meta", false)
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta name="author" content="Aleksandr Dubrovskyi" />
    <meta content="index, follow" name="robots">
    <link rel="icon" type="image/png" href="@Url.Content("~/Content/images/favicon.ico")">
    <link href="@Url.Content("~/Content/bootstrap.min.css")" rel="stylesheet" type="text/css" />
    <link href="@Url.Content("~/Content/styleNew.css")" rel="stylesheet" type="text/css" />
    <link href="@Url.Content("~/Content/validation.css")" rel="stylesheet" type="text/css" />
    <script src="@Url.Content("~/Scripts/jquery-1.8.0.min.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/bootstrap.min.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/site.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/jquery.cookie.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/jQuery.flashMessage.js")" type="text/javascript"></script>
    @RenderSection("head", false)
    @RenderSection("scripts", false)
    <script>
        (function (i, s, o, g, r, a, m) {
            i['GoogleAnalyticsObject'] = r; i[r] = i[r] || function () {
                (i[r].q = i[r].q || []).push(arguments)
            }, i[r].l = 1 * new Date(); a = s.createElement(o),
            m = s.getElementsByTagName(o)[0]; a.async = 1; a.src = g; m.parentNode.insertBefore(a, m)
        })(window, document, 'script', '//www.google-analytics.com/analytics.js', 'ga');

        ga('create', 'UA-41407875-1', 'ffi-eco.com');
        ga('send', 'pageview');

    </script>
</head>
<body>
    <div class="container">
        <header>
            <a href="/">
                <img class="logo" alt="logo" src="@Url.Content("~/Content/images/ffi-eco-logo.png")"/>
            </a>
            <div class="pull-right">
                <div class="row-fluid">
                    <div class="span7">
                        @Html.Partial("_LogOnPartial")
                    </div>
                    <div class="span5">
                        <div class="language-selection">
                            <a href="@Url.Action("ChangeCulture", "Home", new { lang = "uk-UA", returnUrl = Request.Url.ToString() })" title="Українська">
                                <img src="@Url.Content("~/Content/images/ua_flag.png")" alt="українська"/>
                            </a><a href="@Url.Action("ChangeCulture", "Home", new { lang = "ru-RU", returnUrl = Request.Url.ToString() })" title="Русский">
                                    <img src="@Url.Content("~/Content/images/ru_flag.png")" alt="русский"/>
                                </a>@*        <a href="@Url.Action("ChangeCulture", "Home", new { lang = "en-US", returnUrl = Request.Url.ToString() })" title="English">*@
                            @*            <img src="@Url.Content("~/Content/images/en.png")"/>*@ @*        </a>*@
                        </div>
                    </div>
                </div>
                @if (partner != null)
                {
                    <div class="row-fluid">
                    <a class="btn-green-gradient" href="@partnerLink">@Resources.labels.PartnerPanel
                    </a>
                </div>
                }
            </div>
            <div class="pull-right banner">
                @if (siteOnwer.Banners.Any())
                {
                    var banner = siteOnwer.Banners.First();
                    <a href="@banner.Url" target="_blank">
                        <img src="@Url.Action("GetImage", "Banners", new { id = banner.Id })"/>
                    </a>    
                }
            </div>
        </header>
        <section id="main">
            @Html.Partial("_Flash")

            @RenderSection("slideshow", false)
            @Html.Partial("_NavPartial")

            @RenderBody()

        </section>
        <footer>
            <div class="bg-green social">
                <ul class="socialNetworks">
                    <li>
                        <a class="vkontakte" href="http://vk.com/ffi_eco_com" target="_blank"></a>
                    </li>
                    <li>
                        <a class="youtube" href="http://www.youtube.com/channel/UCQAuB1WGvv7m5c2X0dLwisw" target="_blank"></a>
                    </li>
                    <li>
                        <a class="twitter" href="skype:FFI-ECO?chat" target="_blank"></a>
                    </li> 
                    @if (@ViewContext.RouteData.Values["controller"].ToString() == "Products")
                    {
                        <li>
                            <a class="cart" href="@Url.Action("Cart", "Products")" target="_blank"></a>
                        </li>
                    }
                </ul>
            </div>
            <div class="bg-green copyright"> Copyright © 2012-2013 FFI ECO </div>
        </footer>

        @RenderSection("footer_seo", false)
    </div>
</body>
</html>

WestuaFFI/Internet/Views/Shared/_LayoutFluid.cshtml
<!DOCTYPE html>
<html>
<head>
    <title>@ViewBag.Title</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <link href="@Url.Content("~/Content/bootstrap.min.css")" rel="stylesheet" type="text/css" />    
    <link href="@Url.Content("~/Content/site.css")" rel="stylesheet" type="text/css" />
    <link href="@Url.Content("~/Content/bootstrap-responsive.min.css")" rel="stylesheet" type="text/css" />
</head>
<body>
<div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container-fluid">
          <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="#">Twitter Bootstrap MVC</a>          
          @Html.Partial("_LogOnPartial")
          <div class="nav-collapse">
            @Html.Partial("_NavPartial")
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container-fluid">
      <div class="row-fluid">
        <div class="span3">
          @Html.Partial("_SidebarPartial")
        </div>
        <div class="span9">
            @RenderBody()
        </div>
      </div>

      <hr />

      <footer>
        <p>&copy; Company 2012</p>
      </footer>

    </div><!--/.fluid-container-->
    <script src="@Url.Content("~/Scripts/jquery-1.8.0.min.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/bootstrap.min.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/site.js")" type="text/javascript"></script>
</body>
</html>

WestuaFFI/Internet/Views/Shared/_LayoutOld.cshtml
@using Internet.Helpers
@using Internet.Models
@using Internet.RoutingHelpers
@{
    var siteOnwer = SubdomainHelper.GetSiteOwner();
    var partner = Partner.CurrentUserAsPartner;
    var partnerLinkText = partner == null ? Resources.labels.BecomePartner : Resources.labels.PartnerPanel;
    var partnerLink = partner == null ? Url.Action("Business", "Articles") : Url.Action("Edit", "Partners", new { id = User.Identity.Name });
}
<!DOCTYPE html>
<html>
<head>
    <title>@Resources.labels.Title - @ViewBag.Title</title>
    <meta charset="windows-1251">
    @RenderSection("meta", false)
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta name="author" content="Aleksandr Dubrovskyi" />
    <meta content="index, follow" name="robots">
    <link rel="icon" type="image/png" href="@Url.Content("~/Content/images/favicon.ico")">
    <link href="@Url.Content("~/Content/bootstrap.min.css")" rel="stylesheet" type="text/css" />
    <link href="@Url.Content("~/Content/style.css")" rel="stylesheet" type="text/css" />
    <link href="@Url.Content("~/Content/validation.css")" rel="stylesheet" type="text/css" />
    <script src="@Url.Content("~/Scripts/jquery-1.8.0.min.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/bootstrap.min.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/captify.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/site.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/jquery.cookie.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/jQuery.flashMessage.js")" type="text/javascript"></script>
    @RenderSection("head", false)
    @RenderSection("scripts", false)
    <script>
        (function (i, s, o, g, r, a, m) {
            i['GoogleAnalyticsObject'] = r; i[r] = i[r] || function () {
                (i[r].q = i[r].q || []).push(arguments)
            }, i[r].l = 1 * new Date(); a = s.createElement(o),
            m = s.getElementsByTagName(o)[0]; a.async = 1; a.src = g; m.parentNode.insertBefore(a, m)
        })(window, document, 'script', '//www.google-analytics.com/analytics.js', 'ga');

        ga('create', 'UA-41407875-1', 'ffi-eco.com');
        ga('send', 'pageview');

    </script>
</head>
<body>
    <div class="container">
        <header>
            <a href="/">
                <img alt="logo" src="@Url.Content("~/Content/images/logo.png")"/>
            </a>
            <div class="pull-right">
                <div class="row-fluid">
                    <div class="span8">
                        @Html.Partial("_LogOnPartial")
                    </div>
                    <div class="span4">
                        <div class="language-selection">
                            <a href="@Url.Action("ChangeCulture", "Home", new { lang = "uk-UA", returnUrl = Request.Url.ToString() })" title="Українська">
                                <img src="@Url.Content("~/Content/images/ua_flag.png")" alt="українська"/>
                            </a><a href="@Url.Action("ChangeCulture", "Home", new { lang = "ru-RU", returnUrl = Request.Url.ToString() })" title="Русский">
                                <img src="@Url.Content("~/Content/images/ru_flag.png")" alt="русский"/>
                            </a>@*        <a href="@Url.Action("ChangeCulture", "Home", new { lang = "en-US", returnUrl = Request.Url.ToString() })" title="English">*@
                            @*            <img src="@Url.Content("~/Content/images/en.png")"/>*@ @*        </a>*@
                        </div>
                    </div>
                </div>
                <div class="row">
                    @Html.Partial("_ShoppingCart")
                    <a class="btn-large btn-danger" href="@partnerLink">@partnerLinkText
                    </a>
                </div>
            </div>
            <div class="pull-right banner">
                @if (siteOnwer.Banners.Any())
                {
                    var banner = siteOnwer.Banners.First();
                    <a href="@banner.Url" target="_blank">
                        <img src="@Url.Action("GetImage", "Banners", new { id = banner.Id })"/>
                    </a>    
                }
            </div>
        </header>
        <section id="main">
            @Html.Partial("_Flash")
            <div class="row-fluid">
                <div class="span10">
                    @RenderBody()
                </div>
                <div class="span2">
                    <div class="pull-right">
                        @Html.Partial("_NavPartial")
                    </div>
                </div>
            </div>
        </section>
        <footer>
            @RenderSection("footer", false)
        </footer>
    </div>
</body>
</html>

WestuaFFI/Internet/Views/Shared/_LogOnPartial.cshtml
<ul class="nav pull-right username">
    @if (Request.IsAuthenticated)
    {

        <li class="dropdown"><a href="#" class="dropdown-toggle" data-toggle="dropdown">@User.Identity.Name
            <b class="caret"></b></a>
            <ul class="dropdown-menu">
                <li>@Html.ActionLink(@Resources.labels.PartnerPanel, "Edit", "Partners", new { id = User.Identity.Name }, null)
                </li>
                <li>@Html.ActionLink(@Resources.labels.AccountChangePassword, "ChangePassword", "Account")
                </li>
                <li>@Html.ActionLink(@Resources.labels.LogOff, "LogOff", "Account") </li>
            </ul>
        </li>
    }
    else
    {

        <li class="dropdown"><a href="#" class="dropdown-toggle" data-toggle="dropdown">@Resources.labels.Guest
            <b class="caret"></b></a>
            <ul class="dropdown-menu">
                <li>@Html.ActionLink(@Resources.labels.LogOn, "LogOn", "Account") </li>
                <li>@Html.ActionLink(@Resources.labels.NewAccountTitle, "Business", "Articles")
                </li>
            </ul>
        </li>
    }
</ul>

WestuaFFI/Internet/Views/Shared/_NavPartial.cshtml
<nav>
    <div class="row-fluid">
        <div style="margin-top: 20px;" class="pull-left">
            <div class="font-large-green pull-left" style="width: 130px;">
                @Resources.labels.KnowMore
            </div>
            <div class="pull-left arrow-green-right">
            </div>
        </div>
        <div class="pull-left">
            <ul class="menu">
                <li>
                    <a href="@Url.Action("GettingStarted", "Articles")">
                        <div class="menu-item-icon">
                            <img src="@Url.Content("~/Content/images/menu/start.png")" style="margin-top: 5px;"/>
                        </div>
                        <div class="menu-item-title">@Resources.labels.Instruction</div>
                    </a>
                </li>
                <li>
                    <a href="@Url.Action("Index", "Results")">
                        <div class="menu-item-icon">
                            <img src="@Url.Content("~/Content/images/menu/chart.png")" />
                        </div>
                        <div class="menu-item-title">@Resources.labels.PracticalResults</div>
                    </a>
                </li>

                <li>
                    <a href="@Url.Action("HowItWorks", "Articles")">
                        <div class="menu-item-icon">
                            <img src="@Url.Content("~/Content/images/menu/settings.png")" style="margin-top: 5px;"/>
                        </div>
                        <div class="menu-item-title">@Resources.labels.HowItWorks</div>
                    </a>
                </li>
                <li>
                    <a href="@Url.Action("Index", "FAQs")">
                        <div class="menu-item-icon">
                            <img src="@Url.Content("~/Content/images/menu/question.png")" style="margin-top: 5px;"/>
                        </div>
                        <div class="menu-item-title">@Resources.labels.Faq</div>
                    </a>
                </li>
                <li>
                    <a href="@Url.Action("Contacts", "Home")">
                        <div class="menu-item-icon">
                            <img src="@Url.Content("~/Content/images/menu/contacts.png")" style="margin-top: 5px;"/>
                        </div>
                        <div class="menu-item-title">@Resources.labels.Contacts</div>
                    </a>
                </li>
            </ul>
        </div>
    </div>

</nav>

WestuaFFI/Internet/Views/Shared/_ShoppingCart.cshtml
<a href="@Url.Action("Cart", "Products")">
    <img src="@Url.Content("~/Content/images/add-to-cart-icon.png")"  style="margin-right: 50px; margin-top: -15px;" alt="@Resources.labels.Cart"/>
</a>

WestuaFFI/Internet/Views/Shared/_SidebarPartial.cshtml
<div class="well sidebar-nav">
    <ul class="nav nav-list">
        <li class="nav-header">Sidebar</li>
        <li class="active"><a href="#">Link</a></li>
        <li><a href="#">Link</a></li>
        <li><a href="#">Link</a></li>
        <li><a href="#">Link</a></li>
        <li class="nav-header">Sidebar</li>
        <li><a href="#">Link</a></li>
        <li><a href="#">Link</a></li>
        <li><a href="#">Link</a></li>
        <li><a href="#">Link</a></li>
        <li><a href="#">Link</a></li>
        <li><a href="#">Link</a></li>
        <li class="nav-header">Sidebar</li>
        <li><a href="#">Link</a></li>
        <li><a href="#">Link</a></li>
        <li><a href="#">Link</a></li>
    </ul>
</div>
<!--/.well -->

WestuaFFI/Internet/Views/Shared/_Slideshow.cshtml
<div class="slider-wrapper theme-default">
    <div id="slider" class="nivoSlider">
        <img src="images/toystory.jpg" data-thumb="images/toystory.jpg" alt="" />
        <a href="http://dev7studios.com">
            <img src="images/up.jpg" data-thumb="images/up.jpg" alt="" title="This is an example of a caption" />
        </a>
        <img src="images/walle.jpg" data-thumb="images/walle.jpg" alt="" data-transition="slideInLeft" />
        <img src="images/nemo.jpg" data-thumb="images/nemo.jpg" alt="" title="#htmlcaption" />
    </div>
    <div id="htmlcaption" class="nivo-html-caption">
        <strong>This</strong> is an example of a <em>HTML</em> caption with <a href="#">a link</a>.
    </div>
</div>